# import

In [1]:
import pandas as pd
import numpy as np
import random
import os

# map file data

In [4]:
excel_data = pd.ExcelFile("excel.xlsx")

customer_data = pd.read_excel(excel_data, sheet_name='Customer')
product_data = pd.read_excel(excel_data, sheet_name='Product')
store_data = pd.read_excel(excel_data, sheet_name='Store')
state_data = pd.read_excel(excel_data, sheet_name='State')
sell_data = pd.read_excel(excel_data, sheet_name='Sell')

product_data

,ProductID,ProductName,Description,Category,UnitCost,UnitPrice
0,101,Smart TV,4K Ultra HD Smart LED TV,Television,500,800
1,102,Smartphone,Latest Model Smartphone,Mobile,300,600
2,103,Laptop,High-Performance Laptop,Computer,700,1200
3,104,Tablet,Lightweight Tablet,Mobile,200,400
4,105,Smartwatch,Fitness Tracking Smartwatch,Wearable,150,300
5,106,Headphones,Noise-Canceling Bluetooth Headphones,Audio,100,200
6,107,Camera,DSLR Camera with Lens Kit,Photography,800,1200
7,108,Gaming Console,Next-Gen Gaming Console,Gaming,400,600
8,109,Drone,High-Quality Aerial Drone,Gadgets,300,600
9,110,Fitness Tracker,Activity Tracker with Heart Rate Monitor,Wearable,80,150
10,111,Desktop Computer,Powerful Desktop Computer,Computer,1000,1500
11,112,Wireless Speaker,Portable Bluetooth Speaker,Audio,50,100
12,113,E-reader,E-Ink Display E-reader,Reading,120,250
13,114,Portable Charger,High-Capacity Power Bank,Accessories,30,60
14,115,Smart Home Hub,Centralized Smart Home Control Hub,Smart Home,150,300
15,116,VR Headset,Virtual Reality Headset,Gaming,300,500
16,117,External Hard Drive,Portable External Hard Drive,Accessories,80,150
17,118,Bluetooth Earbuds,True Wireless Bluetooth Earbuds,Audio,60,120
18,119,Action Camera,Waterproof Action Camera,Photography,200,400
19,120,Portable Projector,Mini Portable Projector,Accessories,150,300
20,121,Wireless Mouse,Ergonomic Wireless Mouse,Accessories,20,40
21,122,Dash Cam,Full HD Dash Cam,Automotive,100,200
22,123,Gaming Keyboard,Mechanical Gaming Keyboard,Gaming,80,150
23,124,Wireless Router,Dual-Band Wireless Router,Networking,80,150
24,125,Compact Digital Camera,Compact Digital Camera,Photography,150,300
25,126,Portable Bluetooth Keyboard,Foldable Bluetooth Keyboard,Accessories,40,80
26,127,Home Security Camera,Indoor/Outdoor Security Camera,Smart Home,100,200
27,128,USB-C Docking Station,Multiport USB-C Docking Station,Accessories,80,150
28,129,Gaming Mouse,High-Precision Gaming Mouse,Gaming,60,120
29,130,Wireless Charging Pad,Qi Wireless Charging Pad,Accessories,30,60
30,131,Fitness Smart Scale,Bluetooth Fitness Smart Scale,Health,50,100
31,132,Noise-Canceling Earbuds,Wireless Noise-Canceling Earbuds,Audio,100,200
32,133,Mini Drone,Pocket-Sized Mini Drone,Gadgets,50,100
33,134,Portable SSD,External Portable SSD,Accessories,100,200
34,135,Smart Doorbell,Video Doorbell with Two-Way Audio,Smart Home,150,300
35,136,Mechanical Keyboard,RGB Backlit Mechanical Keyboard,Accessories,80,150
36,137,USB-C Charging Cable,USB-C Fast Charging Cable,Accessories,20,40
37,138,Gaming Headset,Surround Sound Gaming Headset,Gaming,80,150
38,139,Smart Plug,Wi-Fi Smart Plug,Smart Home,20,40
39,140,Fitness Smartwatch,GPS Fitness Smartwatch,Wearable,150,300
40,141,Power Strip,Surge Protector Power Strip,Accessories,30,60
41,142,Wireless Gaming Controller,Bluetooth Gaming Controller,Gaming,60,120
42,143,USB-C Hub,Multiport USB-C Hub,Accessories,40,80
43,144,Sleep Headphones,Wireless Bluetooth Sleep Headphones,Audio,100,200
44,145,Car Phone Mount,Universal Car Phone Mount,Automotive,20,40
45,146,RGB Gaming Mouse,RGB LED Gaming Mouse,Gaming,40,80
46,147,Laptop Stand,Ergonomic Laptop Stand,Accessories,20,40
47,148,WiFi Range Extender,Dual-Band WiFi Range Extender,Networking,50,100
48,149,Bluetooth FM Transmitter,Car Bluetooth FM Transmitter,Automotive,30,60
49,150,Wireless Charging Stand,Qi Wireless Charging Stand,Accessories,40,80

In [21]:
sell_data

,ResultID,Date,Product,Price,Quantity,Revenue,Customer,Customer Address
0,1,2024-06-04,Smart TV,800.000000,12,9600,John Smith,"123 Main Street, Los Angeles"
1,2,2024-10-13,Smartphone,600.000000,8,4800,Emily Johnson,"456 Elm Avenue, New York City"
2,3,2024-04-12,Laptop,1200.000000,5,6000,Michael Williams,"789 Oak Boulevard, Chicago"
3,4,2024-12-22,Tablet,400.000000,15,6000,Jennifer Brown,"1000 Pine Drive, Houston"
4,5,2024-01-04,Smartwatch,300.000000,20,6000,David Miller,"123 Maple Street, Phoenix"
...,...,...,...,...,...,...,...,...
155,156,2024-06-01,Compact Digital Camera,686.256961,15,4500,Henry Scott,NaN
156,157,2024-06-14,Portable Bluetooth Keyboard,133.265017,10,2000,Amelia Clark,NaN
157,158,2024-06-27,Home Security Camera,1000.307591,6,900,Logan Hall,NaN
158,159,2024-07-30,USB-C Docking Station,811.012459,12,1800,Zoe Young,NaN
159,160,2024-11-10,USB-C Docking Station,674.719358,15,4500,Henry Scott,NaN

# random date from sell_data

In [15]:
# Define the date range
start_date = pd.to_datetime('2024-01-01')
end_date = pd.to_datetime('2024-12-31')

# Function to generate a random date
def random_date(start, end):
    return start + pd.to_timedelta(np.random.randint(0, (end - start).days), unit='D')

# Apply the random_date function to generate random dates
sell_data['Date'] = [random_date(start_date, end_date) for _ in range(len(sell_data))]

# Display the first few rows of the updated sell_data
sell_data.head()

,ResultID,Date,Product,price,Quantity,Revenue,Customer,Customer Address
0,1,2024-06-04,Smart TV,800.0,12,9600,John Smith,"123 Main Street, Los Angeles"
1,2,2024-10-13,Smartphone,600.0,8,4800,Emily Johnson,"456 Elm Avenue, New York City"
2,3,2024-04-12,Laptop,1200.0,5,6000,Michael Williams,"789 Oak Boulevard, Chicago"
3,4,2024-12-22,Tablet,400.0,15,6000,Jennifer Brown,"1000 Pine Drive, Houston"
4,5,2024-01-04,Smartwatch,300.0,20,6000,David Miller,"123 Maple Street, Phoenix"

# random price from sell_data

In [20]:
# Define the range for random prices
min_price = 5
max_price = 1500

# Function to generate a random price within the given range
def random_price(min_price, max_price):
    return np.random.uniform(min_price, max_price)

# Apply the random_price function to rows where 'Price Each' is NaN
sell_data['Price'] = sell_data['Price'].apply(
    lambda x: random_price(min_price, max_price) if pd.isna(x) else x
)

# Display the first few rows of the updated sell_data
sell_data.head()

,ResultID,Date,Product,Price,Quantity,Revenue,Customer,Customer Address
0,1,2024-06-04,Smart TV,800.0,12,9600,John Smith,"123 Main Street, Los Angeles"
1,2,2024-10-13,Smartphone,600.0,8,4800,Emily Johnson,"456 Elm Avenue, New York City"
2,3,2024-04-12,Laptop,1200.0,5,6000,Michael Williams,"789 Oak Boulevard, Chicago"
3,4,2024-12-22,Tablet,400.0,15,6000,Jennifer Brown,"1000 Pine Drive, Houston"
4,5,2024-01-04,Smartwatch,300.0,20,6000,David Miller,"123 Maple Street, Phoenix"

# calculate revenue

In [22]:
sell_data['Revenue'] = sell_data['Price'] * sell_data['Quantity']

# generate data

In [18]:
products = product_data["ProductName"]
prices = product_data["UnitPrice"]
addresses = customer_data["Address"] + ", " + customer_data["City"]
    
# Merge sell_data with product_data to get product names
sell_data = sell_data.merge(product_data[['ProductID', 'ProductName']], on='ProductID', how='left')

# Merge sell_data with customer_data to get customer names and addresses
sell_data = sell_data.merge(customer_data[['CustomerID', 'CustomerName']], on='CustomerID', how='left')

sell_data['Customer Address'] = addresses

sell_data['Price'] = prices

# Drop the ProductID and CustomerID columns as they are no longer needed
sell_data.drop(columns=['ProductID', 'CustomerID'], inplace=True)

# Rename columns to match the required format
sell_data.rename(columns={
    'ProductName': 'Product',
    'CustomerName': 'Customer'
}, inplace=True)

sell_data = sell_data[['ResultID', 'Date', 'Product', 'price', 'Quantity', 'Revenue', 'Customer', 'Customer Address']]

# Display the first few rows of the updated sell_data
sell_data.head()

KeyError: 'ProductID'

# save data

In [23]:
# Convert 'Date' column to datetime format
sell_data['Date'] = pd.to_datetime(sell_data['Date'])

output_dir = './data/monthly_sales_2024'
os.makedirs(output_dir, exist_ok=True)

# Split the data by month and save each month to a separate CSV file
for month in range(1, 13):
    monthly_data = sell_data[sell_data['Date'].dt.month == month]
    monthly_file_path = os.path.join(output_dir, f'sales2024_{month:01}.csv')
    monthly_data.to_csv(monthly_file_path, index=False)

output_dir

'./data/monthly_sales_2024'